### ISSUE TITLE
Usage of pure rust SCCA library

### ISSUE THREAD

**Issue by SecSamDev** [dfir-dd/dfir-toolkit#23]
I have developed a pure rust prefetch parser, it is still in development and is designed to work with the Forensic-RS framework, but it can work in this project so as not to use bindings to C code.

[https://crates.io/crates/frnsc-prefetch](https://crates.io/crates/frnsc-prefetch)

It does not use the Windows-exclusive RtlDecompressBuffer function that other implementations use, which allows it to be used on any platform compatible with the standard Rust library.
It also gives you accurate traces and metrics, such as which blocks were loaded into runtime memory, as a resource, or fetched from disk without going through the prefetch.

The logs generated during processing can be accessed through Rust code by initializing the logger. They are not sent directly to stdout or stderr. [logger](https://github.com/ForensicRS/forensic-rs/blob/b007b52c3b1d2e924f5bde1074829f0c08c846e8/src/logging/mod.rs#L74)

You can also check for anomalies detected during processing through the notification system and create hooks when certain anomalies occur. [notifications](https://github.com/ForensicRS/forensic-rs/blob/main/src/notifications/mod.rs)

**Comment by janstarke** [comment]
I tried to use your library and, guess what, it is working pretty well. Is this something you had in mind?

**Comment by SecSamDev** [comment]
I'm glad to hear it works.
It was one of the Windows artifacts that I wanted to know more about. I am also working on other parsers and in parallel improving the usability of the framework.
So the feedback is appreciated.

**Comment by janstarke** [comment]
I see a lot of crates flying around which all implement the same or similar windows data types, such as several time stamp format. There are implementations in my crates, in yours as well, in the ones by @omerbenamram and so on. I think we should concentrate them in special crates in order improve code reuse. What do you think about it?
