### ISSUE TITLE
Regdump | Creation of timeline fails, when the given transaction log is empty

### ISSUE THREAD

**Issue by Bitbee0** [dfir-dd/dfir-toolkit#29]
I get the following error message, when I try to create a timeline from the registry with `regdump` and specify a transaction log, that is empty.
```sh
$ regdump -L ntuser.dat.LOG1 -L ntuser.dat.LOG2 -b NTUSER.DAT > ntuser.body

Error: AssertFail at 0x0: "! log_entries.is_empty()"
```

It would be cool when the program continues to process the contents despite an empty transaction log and outputs a small warning that the transaction log is empty.

**Comment by janstarke** [comment]
Can you please give it a try?

**Comment by Bitbee0** [comment]
Works now :thumbsup:
